### ISSUE TITLE
Poetry could not find a pyproject.toml file in {} or its parents

### ISSUE THREAD

**Issue by rolltidehero** [Quoorex/checket#1]
`poetry install

  RuntimeError

  Poetry could not find a pyproject.toml file in /home/hero or its parents

  at .local/lib/python3.8/site-packages/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )`

**Comment by Quoorex** [comment]
You have to navigate to the folder containing this project first, before running `poetry install`. If you're running Linux, Windows or macOS, you can do that by using the command `cd`.
This problem has nothing to do with the software itself, but I will look into updating the README to make things more clear.
